/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {

    public static void main(String[] args){

    }
    public boolean someLibraryMethod() {
        return true;
    }

    public int [] roll (int n){
        Random r = new Random();
        int[] rolls = new int[n];
        for (int i = 0; i < n; i++){
            int rNum = r.nextInt(6);
            rolls[i] = rNum + 1;
        }
        return rolls;

    }

    public boolean containsDuplicates (int[] arr){
        for (int i = 0; i < arr.length; i++){
            for (int j = 1; j < arr.length; j++){
            if (i == j) continue;
            if (arr[i] == arr[j])
                    return true;
                }
        }
        return false;
    }

   public int arrayAverage(int[] arr){
       int [] array = {1,2,3,4,5,6,7,10,15,17};

       int length = array.length;

       int sum = 0;

       for (int i = 0 ; i < array.length; i++){
           sum += array[i];
       }
       double average = sum / length;

       return sum;
   }



}


