/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        String fPath = "app/src/main/resources/gates.js";
        System.out.println(linter(fPath));
    }

    public static String linter(String file) {
        int lineNumber = 0;

        StringBuilder eMessage = new StringBuilder();
        try {
            Path lPath = Paths.get(file);
            Scanner scanner = new Scanner(new BufferedReader(new FileReader(file)));

            while (scanner.hasNextLine()) {
                lineNumber++;
                String line = scanner.nextLine();
                if (line.isEmpty() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else")) {
                    continue;
                } else {
                    eMessage.append("Line ").append(lineNumber).append(": No semicolon.\n ");
                }
            }
        } catch (IOException e) {
            System.out.println(e + "Error Line" + lineNumber);
        }
        if (eMessage.length() == 0) {
            eMessage.append("File is empty.");
        }
        return eMessage.toString();
    }
}